# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml -f compose.rviz.lan.yaml up

services:

  # ROS Galactic
  rviz:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  map-publisher:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  heatmapping_planner:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION