# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml up

services:

  rviz:
    image: husarion/rviz2:galactic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz

    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1

  map-publisher:
    build: .
    command: ros2 run floor_heat_mapper floor_heat_mapper