# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.mapping.yaml -f compose.rosbot.lan.yaml up
version: "3"
services:
  micro-ros-agent:
    network_mode: service:husarnet-heatmapping
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet-heatmapping:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_rosbot:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot
      - JOINCODE