# Quick Start (at fist stop ROS Master if working on host)
# $ docker-compose -f compose.rosbot.heatmapping.yaml  -f compose.rosbot.heatmapping.lan.yaml up
version: "3"
services:

  micro-ros-agent:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION


