# Quick Start
# $ docker compose -f compose.rosbot.hardware.yaml up

services:

  rplidar:
    image: husarion/rplidar:galactic
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: >
      ros2 launch rplidar_ros2 rplidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE}
  bridge:
    image: husarion/ros:galactic-ros1-bridge
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      ros2 run ros1_bridge dynamic_bridge
  ros-master:
    image: ros:noetic-ros-core
    restart: unless-stopped
    command: stdbuf -o L roscore

  rosbot:
    image: husarion/rosbot:noetic
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT}
    environment:
      - SERIAL_PORT
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      roslaunch --wait rosbot_bringup rosbot_docker.launch