# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml -f compose.rviz.lan.yaml up

services:

  rviz:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION