# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.yaml -f compose.rosbot.lan.yaml up

services:

  rplidar:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID

  nav2:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID

  slam-toolbox:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID

  bridge:
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_DOMAIN_ID

  ros-master:
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=127.0.0.1

  rosbot:
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311