# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml up

services:

  rviz:
    image: husarion/rviz2:humble
    volumes:
      - ./robot_model:/robot_model
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
  floor-heat-mapper:
    build: .
    command: ros2 launch floor_heat_mapper  floor_heat_mapper.launch.py sync_auto:=${SYNC_AUTO} async_auto:=${ASYNC_AUTO}